name: github actions with Terraform

  working-directory: ./ag_module/example

on:
  push:
    branches: ["main", "master"]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1


    steps: 
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

      
    - name: Terraform Plan
      id: plan
      run: terraform plan

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve

    - name: Terraform destroy
      id: destroy
      run: terraform destroy -auto-approve



